# Generated by Django 5.2.8 on 2026-03-15 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gender', models.CharField(blank=True, max_length=50)),
                ('dob', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('current_weight_kg', models.FloatField(blank=True, null=True)),
                ('current_height_cm', models.FloatField(blank=True, null=True)),
                ('target_weight_kg', models.FloatField(blank=True, null=True)),
                ('target_height_cm', models.FloatField(blank=True, null=True)),
                ('goal', models.CharField(blank=True, max_length=100)),
                ('activity_level', models.CharField(blank=True, max_length=50)),
                ('eating_realities', models.TextField(blank=True)),
                ('medical_restrictions', models.TextField(blank=True)),
                ('allergies', models.TextField(blank=True)),
                ('dislikes', models.TextField(blank=True)),
                ('cooking_skills', models.CharField(blank=True, max_length=100)),
                ('diet', models.CharField(blank=True, max_length=100)),
                ('religion', models.CharField(blank=True, max_length=100)),
                ('occupational_status', models.CharField(blank=True, max_length=100)),
                ('works_at', models.CharField(blank=True, max_length=255)),
                ('income_level', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('day_streak', models.IntegerField(default=0)),
                ('profile_completed_awarded', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
