# Generated by Django 5.2.8 on 2026-03-20 08:04

import django.db.models.deletion
import django.utils.timezone
import profiles.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupabaseUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', profiles.models.SupabaseUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gender', models.CharField(blank=True, max_length=50)),
                ('dob', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('current_weight_kg', models.FloatField(blank=True, null=True)),
                ('current_height_cm', models.FloatField(blank=True, null=True)),
                ('target_weight_kg', models.FloatField(blank=True, null=True)),
                ('target_height_cm', models.FloatField(blank=True, null=True)),
                ('goal', models.CharField(blank=True, max_length=100)),
                ('activity_level', models.CharField(blank=True, max_length=50)),
                ('eating_realities', models.TextField(blank=True)),
                ('medical_restrictions', models.TextField(blank=True)),
                ('allergies', models.TextField(blank=True)),
                ('dislikes', models.TextField(blank=True)),
                ('cooking_skills', models.CharField(blank=True, max_length=100)),
                ('diet', models.CharField(blank=True, max_length=100)),
                ('religion', models.CharField(blank=True, max_length=100)),
                ('occupational_status', models.CharField(blank=True, max_length=100)),
                ('works_at', models.CharField(blank=True, max_length=255)),
                ('income_level', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('day_streak', models.IntegerField(default=0)),
                ('profile_completed_awarded', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
