# Generated by Django 5.2.8 on 2025-12-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_completed_awarded',
            field=models.BooleanField(default=False),
        ),
    ]
