# Generated by Django 5.2.8 on 2026-02-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_profile_avatar_alter_profile_day_streak_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='weight',
            new_name='activity_level',
        ),
        migrations.AddField(
            model_name='profile',
            name='allergies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='cooking_skills',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_height_cm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_weight_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='dislikes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='eating_realities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='goal',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='medical_restrictions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='target_height_cm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='target_weight_kg',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
