# Generated by Django 5.2.8 on 2026-03-31 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_referral_constraints'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='referral',
            new_name='profiles_re_referre_a54a29_idx',
            old_name='profiles_refer_referrer_4532db_idx',
        ),
        migrations.RenameIndex(
            model_name='referral',
            new_name='profiles_re_referre_d7ff33_idx',
            old_name='profiles_refer_referred_8e9f0a_idx',
        ),
        migrations.AddField(
            model_name='profile',
            name='referred_by',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
