PROFILE_COMPLETION_FIELDS = [
    "gender",
    "dob",
    "current_weight_kg",
    "current_height_cm",
    "target_weight_kg",
    "goal",
    "activity_level",
    "eating_realities",
    "medical_restrictions",
    "allergies",
    "cooking_skills",
    "diet",
    "religion",
    "region",
]