# Generated by Django 5.2.8 on 2026-03-20 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PoaPointsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('LOCKED', 'Locked')], default='ACTIVE', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='poa_wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'poa_points_account',
            },
        ),
        migrations.CreateModel(
            name='PoaPointsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('type', models.CharField(max_length=80)),
                ('reference_key', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='rewards.poapointsaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='poa_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'poa_points_transaction',
            },
        ),
        migrations.CreateModel(
            name='Redemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_key', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed')], default='PENDING', max_length=12)),
                ('cost', models.PositiveIntegerField()),
                ('provider', models.CharField(blank=True, default='', max_length=80)),
                ('target', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'redemption',
            },
        ),
        migrations.CreateModel(
            name='RewardClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_key', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=80)),
                ('event_id', models.CharField(blank=True, max_length=120, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('APPLIED', 'Applied'), ('REJECTED', 'Rejected'), ('REVERSED', 'Reversed')], default='PENDING', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reward_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reward_claim',
            },
        ),
        migrations.AddIndex(
            model_name='poapointsaccount',
            index=models.Index(fields=['user'], name='poa_points__user_id_eb51a6_idx'),
        ),
        migrations.AddIndex(
            model_name='poapointsaccount',
            index=models.Index(fields=['status'], name='poa_points__status_7ab80c_idx'),
        ),
        migrations.AddIndex(
            model_name='poapointstransaction',
            index=models.Index(fields=['user', 'created_at'], name='poa_points__user_id_3ff90c_idx'),
        ),
        migrations.AddIndex(
            model_name='poapointstransaction',
            index=models.Index(fields=['account', 'created_at'], name='poa_points__account_cc4532_idx'),
        ),
        migrations.AddIndex(
            model_name='poapointstransaction',
            index=models.Index(fields=['type'], name='poa_points__type_92a27d_idx'),
        ),
        migrations.AddConstraint(
            model_name='poapointstransaction',
            constraint=models.UniqueConstraint(fields=('reference_key',), name='uq_poa_tx_reference_key'),
        ),
        migrations.AddIndex(
            model_name='redemption',
            index=models.Index(fields=['user', 'created_at'], name='redemption_user_id_f38e84_idx'),
        ),
        migrations.AddIndex(
            model_name='redemption',
            index=models.Index(fields=['status'], name='redemption_status_b0ca1f_idx'),
        ),
        migrations.AddConstraint(
            model_name='redemption',
            constraint=models.UniqueConstraint(fields=('user', 'reference_key'), name='uq_redemption_user_key'),
        ),
        migrations.AddIndex(
            model_name='rewardclaim',
            index=models.Index(fields=['user', 'status'], name='reward_clai_user_id_389cd5_idx'),
        ),
        migrations.AddIndex(
            model_name='rewardclaim',
            index=models.Index(fields=['reference_key'], name='reward_clai_referen_761c05_idx'),
        ),
        migrations.AddIndex(
            model_name='rewardclaim',
            index=models.Index(fields=['event_type'], name='reward_clai_event_t_a0a455_idx'),
        ),
        migrations.AddConstraint(
            model_name='rewardclaim',
            constraint=models.UniqueConstraint(fields=('user', 'reference_key'), name='uq_reward_claim_user_key'),
        ),
    ]
