# Generated by Django 5.2.8 on 2026-02-20 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='poapointsaccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='poa_wallet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='poapointstransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='poa_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='redemption',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rewardclaim',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reward_claims', to=settings.AUTH_USER_MODEL),
        ),
    ]
