# Generated by Django 5.2.8 on 2025-11-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('flour', 'Flour'), ('dairy', 'Dairy Product'), ('oil', 'Cooking Oil'), ('sugar', 'Sugar'), ('rice', 'Rice'), ('tea', 'Tea'), ('salt', 'Salt'), ('baking_powder', 'Baking Powder'), ('other', 'Other')], max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
