# Generated by Django 5.2.8 on 2025-11-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('flour', 'Flour'), ('dairy', 'Dairy Product'), ('oil', 'Cooking Oil'), ('sugar', 'Sugar'), ('rice', 'Rice'), ('tea', 'Tea'), ('salt', 'Salt'), ('baking_powder', 'Baking Powder'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
